### ISSUE TITLE
Couldn't find matching branch in code

### ISSUE THREAD

**Issue by LeThaiSon** [kevinzakka/form2fit#1]
Hi, I would like to say many thanks for the works you have done. I wonder if the matching branch (show in picture below) is included in the code. I can only find the rotation matching which will output the best similar angle between a pair of pick and place, but can not find the keypoint matching part which should be used to do position alignment. If it's somewhere inside the code please kindly guide me to it. Thank you so much!

![image](https://user-images.githubusercontent.com/12003249/68837873-202d9f80-06f0-11ea-8ddf-96a127cae09f.png)

**Comment by kevinzakka** [comment]
Hey @LeThaiSon,

Unfortunately, we haven't provided the script that takes in raw data and processes it into heightmap, masks, correspondences and suction and place points.

To obtain the correspondences, you'll need to apply the rigid transform describing the relative end-effector rotation from pick to place on the object mask. We do this in heightmap space but you could just as well do it in pixel space.

Hope this helps!

**Comment by LeThaiSon** [comment]
Thank you so much for your immediate respond! Refer to the orignal paper, the matching module is used to establishes correspondences between object picking and kit placement locations. Am I right that it only do pairing correspondense pick and place locations (output from dense pixelwise suction and placement network) or it can do alignment for placing position base on the picking relative position? For example the predict picking position is in center of the object, but the predict placing position is a little bit shift to the left, then without alignment process it can not place the object fit to the box. I think the alignment is calculated in planner (generate p,q value) is that right, but when reading to the planner code I couldn't find something like that. Please correct me if my understanding is wrong! Thank you so much.
![image](https://user-images.githubusercontent.com/12003249/69111121-24bad500-0aaf-11ea-970e-635ec5edd62f.png)
