### ISSUE TITLE
Testing on real robot

### ISSUE THREAD

**Issue by seivazi** [kevinzakka/form2fit#2]
Could you share the code for controlling the UR robot?
If you need any help I will be more than happy to contribute.

**Comment by kevinzakka** [comment]
Hi @seivazi , do you mean the code for automatic data collection or just code to control the UR5 with basic primitives? We unfortunately won't make the latter available anytime soon for this codebase. However, we are planning on releasing a separate basic pip library for controlling the UR5 if there's enough interest.

**Comment by seivazi** [comment]
Hi,
Thank you for fast reply.
I was hopping to get similar code as your previous work with visual-pushing-grasping paper.
For sure basic pip library for controlling the UR5 will be useful.
It will be great if you could share data collection/testing with UR including e.g. camera setup, calibration, ..
I'm planing a similar data collection. If there is no licensing issue only time/resources is main constrain I will be more than happy to take the code further and later with your help share it publicly with more data.

**Comment by kevinzakka** [comment]
I'll let you know if we move forward with the library.
